:bug: fix out of memory issue
Error: memory allocation failed, out of memory
root cause: Since the scratching scratchcard test always accesses the previously
created ScratchCard PDA account, but this ScratchCard added other fields when
implementing the ScratchingCard instruction logic later on, requiring more memory
than the size of the ScratchCard PDA account previously created, an error occurred

Signed-off-by: Shuang-Zi <yang03_15@126.com>